import { Inter } from "next/font/google";
import "./globals.css";
import '../../node_modules/bootstrap/dist/css/bootstrap.css';
import UseImport from "./Extralib/UseImport";
import Admin from "./component/admin/admin";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">      
      <body className={inter.className}>
        <UseImport/>
        <Admin main={children}/>
       </body>
    </html>
  );
}
